/* com_google_android_googlecamera.rs - Handler for cards generated by the android app com.google.android.GoogleCamera

   This file is part of the media-interface project

   Copyright (c) 2026 Efthymios Kritikos

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

use anyhow::{Result, anyhow };
use crate::SourceMediaInterface;
use std::path::{PathBuf,Path};
use crate::helpers::*;
use crate::FileItem;
use crate::helpers::ItemType::*;
use crate::helpers::FileType::*;


pub struct ComGoogleAndroidGoogleCameraInterface;

#[derive(Debug)]
enum GoogleType{
    Raw,
    Ts,
    LongExposure,
    Night,
    PlainVideo,
    Photosphere,
    Portrait,
    Pano,
}

fn file_to_google_type(filename:&str) -> Result<GoogleType> {
    let rest = filename
        .strip_prefix("PXL_")
        .ok_or(anyhow!("Filename {} doesn't start with \"PXL_\"", filename))?;

    // YYYYMMDD_HHMMSSmmm : 18 bytes
    if rest.len() < 18 {
        return Err(anyhow!("Filename {} doesn't even have enough characters to get a timestamp",filename));
    }

    let timestamp = &rest.as_bytes()[..18];

    if timestamp[8] != b'_'
        || ! timestamp[..8].iter().all(u8::is_ascii_digit)
        || ! timestamp[9..].iter().all(u8::is_ascii_digit) {
        return Err(anyhow!("Filename {} doesn't have a valid timestamp",filename));
    }

    match &rest[18..] {
        ".RAW-01.COVER.jpg" | ".RAW-02.ORIGINAL.dng" =>
            Ok(GoogleType::Raw),
        ".TS.mp4" =>
            Ok(GoogleType::Ts),
        ".LONG_EXPOSURE-01.COVER.jpg" | ".LONG_EXPOSURE-02.ORIGINAL.jpg" =>
            Ok(GoogleType::LongExposure),
        ".NIGHT.RAW-01.COVER.jpg" | ".NIGHT.RAW-02.ORIGINAL.dng" =>
            Ok(GoogleType::Night),
        ".mp4" =>
            Ok(GoogleType::PlainVideo),
        ".PHOTOSPHERE.jpg" =>
            Ok(GoogleType::Photosphere),
        ".PORTRAIT.jpg" =>
            Ok(GoogleType::Portrait),
        ".PANO.jpg" =>
            Ok(GoogleType::Pano),
        _ =>
            Err(anyhow!("Unknow google file type for file {}",filename)),
    }
}

////////////////////////////////////////
//         File parsing code          //
////////////////////////////////////////

fn filetype(ext: &str) -> Result<JsonFileInfoTypes> {
    match ext {
        "mp4" => Ok(JsonFileInfoTypes{ file_type:FileVideo,        item_type:ItemVideo }),
        "jpg" => Ok(JsonFileInfoTypes{ file_type:FileImage,        item_type:ItemImage }),
        "dng" => Ok(JsonFileInfoTypes{ file_type:FileImageRaw,     item_type:ItemImage }),
        _ => Err(anyhow!("unkown file extension {:?} trying to determain file type", ext)),
    }
}

impl SourceMediaInterface for ComGoogleAndroidGoogleCameraInterface {
    //TODO: handle case where the thumbnail is in the known missing files and the item needs to be
    //represented by something else
    fn list_thumbnail( &self, _source_media_location: &Path, source_media_card: &Path, _known_missing_files: Vec<PathBuf>) -> Result<Vec<FileItem>> {
        filter_dir(source_media_card, |filename: &str, input_ext: Option<&str>, _path: &PathBuf, path_str: &str| {

            let ext = input_ext.ok_or_else(|| anyhow!("Expected filter_dir to porivde a file extension"))?;

            if match file_to_google_type(filename)? {
                GoogleType::Raw =>  ext == "jpg",
                GoogleType::Ts => true,
                GoogleType::LongExposure => filename.ends_with("01.COVER.jpg"),
                GoogleType::Night => ext == "jpg",
                GoogleType::PlainVideo => true,
                GoogleType::Photosphere => true,
                GoogleType::Portrait => true,
                GoogleType::Pano => true,
            } {
                match ext {
                    "mp4" => Ok(Some(create_part_file(path_str.to_string(), filetype(ext)?, 1, 1, None))),
                    "jpg" => Ok(Some(create_simple_file(path_str.to_string(), filetype(ext)?, None)?)),
                    _ => Err(anyhow!("Unexpected file {}", path_str)),
                }
            } else {
                Ok(None)
            }
        })
    }
    fn list_high_quality( &self, _source_media_location: &Path, source_media_card: &Path, _known_missing_files: Vec<PathBuf>) -> Result<Vec<FileItem>> {
        filter_dir(source_media_card, |filename: &str, input_ext: Option<&str>, _path: &PathBuf, path_str: &str| {

            let ext = input_ext.ok_or_else(|| anyhow!("Expected filter_dir to porivde a file extension"))?;

            if match file_to_google_type(filename)? {
                GoogleType::Raw =>  ext == "dng",
                GoogleType::Ts => true,
                GoogleType::LongExposure => filename.ends_with("02.ORIGINAL.jpg"),
                GoogleType::Night => ext == "dng",
                GoogleType::PlainVideo => true,
                GoogleType::Photosphere => true,
                GoogleType::Portrait => true,
                GoogleType::Pano => true,
            } {
                match ext {
                    "mp4" => Ok(Some(create_part_file(path_str.to_string(), filetype(ext)?, 1, 1, None))),
                    "dng"|"jpg" => Ok(Some(create_simple_file(path_str.to_string(), filetype(ext)?, None)?)),
                    _ => Err(anyhow!("Unexpected file {}", path_str)),
                }
            } else {
                Ok(None)
            }
        })
    }
    fn get_related(&self, _source_media_location: &Path, _source_media_file: &Path, _known_missing_files: Vec<PathBuf>) -> Result<Vec<FileItem>>{
        Err(anyhow!("Badabing"))
    }

    fn name(&self) -> &'static str {
        "com.google.android.GoogleCamera"
    }
}
